enum GamepadMap
{
    LX = 0,
    LY = 1,
    RX = 2,
    RY = 3,
    FACE_BUTTON_DOWN = 0,
    CROSS = 0,
    A = 0,
    FACE_BUTTON_RIGHT = 1,
    CIRCLE = 1,
    B = 1,
    FACE_BUTTON_LEFT = 2,
    SQUARE = 2,
    X = 2,
    FACE_BUTTON_UP = 3,
    TRIANGLE = 3,
    Y = 3,
    L1 = 4,
    LB = 4,
    R1 = 5,
    RB = 5,
    L2 = 6,
    LT = 6,
    R2 = 7,
    RT = 7,
    SELECT = 8,
    SHARE = 8,
    START = 9,
    OPTIONS = 9,
    L3 = 10,
    R3 = 11,
    DPAD_UP = 12,
    DPAD_DOWN = 13,
    DPAD_LEFT = 14,
    DPAD_RIGHT = 15,
    SYSTEM = 16,
    PLAYSTATION = 16,
    XBOX = 16
}

export default GamepadMap;
